CREATE DATABASE IF NOT EXISTS pizzas_db;

USE pizzas_db;

DROP TABLE IF EXISTS pizzas;

CREATE TABLE pizzas (
id int NOT NULL AUTO_INCREMENT,
pizza_name varchar(255) NOT NULL,
devoured BOOLEAN DEFAULT false,
tStamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
dTime DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);
